# Generated by Django 5.0.2 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='lachoshop/images/products/gallery/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(to='shop.imagegallery'),
        ),
    ]
